### ISSUE TITLE
Event could not be sent

### ISSUE THREAD

**Issue by brianary** [bytenik/Seq.App.Slack#13]
When the Slack integration is triggered, we get an error (below) and the event is not successfully sent to the Slack channel. 

I notice that [SlackReactor.cs:123](https://github.com/bytenik/Seq.App.Slack/blob/master/SlackReactor.cs#L123) uses `evt.Data` without first checking it for null. That's the only usage of an object without a null check I can find directly in the `On()` method, where the stack trace suggests the NRE is happening.

Our network has a couple peculiarities that could also be contributing to this issue:

First, for some reason, both the `Proxy` property of `System.Net.WebClient` instances and the `DefaultWebProxy` static property of `System.Net.WebRequest` are null. Several open source programs used properties of `Proxy` or `DefaultWebProxy` without checking for null, causing them to crash with an NRE on our network. I've reported this and fixed it in a few projects where I could. The error below suggests to me that could be the issue here, though I can't find any use of "proxy" in this project.

Second, we use a decrypting firewall that substitutes its own self-signed certificate for sites that we visit. It isn't a proxy, it runs entirely passively. This is a security measure that seems to be becoming more popular, but many libraries & applications (particularly Node-based ones) do not use the (Windows) system cert store to validate certs, instead each bundles their own root CA store. This causes any https traffic to fail with a "self-signed cert" or "could not establish SSL/TLS channel" error, but that isn't what we're getting with the Seq Slack integration, so I don't think this one is the problem.

Some additional logging detail (i.e. line numbers) might help figure this out.

```json
# Seq.App.Slack error event JSON, after a manual trigger
{
  "@t": "2017-07-11T13:56:14.5048723Z",
  "@mt": "The event {EventId} could not be sent to {AppInstanceTitle}.",
  "@m": "The event event-74fb7be3c7b208d4e6ed180000000000 could not be sent to Slack #seq channel.",
  "@i": "e285b3dc",
  "@l": "Error",
  "@x": "System.NullReferenceException: Object reference not set to an instance of an object.\r\n
   at Seq.Slack.SlackReactor.On(Event`1 evt)\r\n
   at Seq.Server.Features.Runner.AppHost.SendLogEventData(ISubscribeTo`1 reactor, StorageEvent se)\r\n
   at Seq.Server.Features.Runner.AppHost.Send(StorageEvent storageEvent)",
  "EventId": "event-74fb7be3c7b208d4e6ed180000000000",
  "AppInstanceTitle": "Slack #seq channel",
  "AppInstanceId": "appinstance-1037",
  "AppId": "hostedapp-1025"
}
```

**Comment by bytenik** [comment]
This should now be resolved in `0.1.10`. If not, please ping back and I'll be more responsive this time. 😄
