### ISSUE TITLE
Using the Slack App after using Alerts in Seqv4

### ISSUE THREAD

**Issue by dampee** [bytenik/Seq.App.Slack#14]
We are running Seq v4.0.60.  If you submit alerts using the slack app, it'll throw a null reference exception when the alert is triggered. 

This is the logged event in slack containing the stack trace:

{"@t":"2017-07-21T08:01:50.5424108Z","@mt":"The event {EventId} could not be sent to {AppInstanceTitle}.","@m":"The event event-00000000000000000000000000000000 could not be sent to Slack RF notifier.","@i":"e285b3dc","@l":"Error","@x":"System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at Seq.Slack.SlackReactor.On(Event`1 evt)\r\n   at Seq.Server.Features.Runner.AppHost.SendLogEventData(ISubscribeTo`1 reactor, StorageEvent se)\r\n   at Seq.Server.Features.Runner.AppHost.Send(StorageEvent storageEvent)","EventId":"event-00000000000000000000000000000000","AppInstanceTitle":"Slack RF notifier","AppInstanceId":"appinstance-130","AppId":"hostedapp-3"}

**Comment by nblumhardt** [comment]
@dampee thanks for the heads-up via the Seq support page 👍 

My guess is we're hitting:

https://github.com/bytenik/Seq.App.Slack/blob/master/SlackReactor.cs#L165

The `Value` property can be `null` here, so `ToString()` would generate `NullReferenceException`.

I'll investigate further and shoot through a PR.
