### ISSUE TITLE
Problem with the URLs in the notifications

### ISSUE THREAD

**Issue by marcinbudny** [bytenik/Seq.App.Slack#21]
Hello,
I'm currently using version 0.2.23. I created an instance that has the Seq base URL configured to a custom value. When sending a single event to the app via events -> select an event -> send to app, the URL that appears in the notification is correct and uses the base url value properly. However if the notification is sent from an alert on a dashboard, both links (the dashboard link and "Explore detected results in Seq" link) point to localhost.

**Comment by nblumhardt** [comment]
Hi Marcin,

When you run `seq.exe config -k api.listenUris` from an administrative command-prompt on your Seq server, is the URL that you want displayed first in the resulting list?

If not, you can use `seq.exe config -k api.listenUris -v "http://...."` to set the listen URLs, with the default URL first.

Does this help?

Best regards,
Nick

**Comment by marcinbudny** [comment]
Hi,
I followed your suggestion and it fixed the problem. Thanks.
Why does the base url setting affect only some of the generated links?

**Comment by nblumhardt** [comment]
Thanks for the follow-up.

The app has a `BaseUrl` setting that it uses to generate URLs itself:

https://github.com/bytenik/Seq.App.Slack/blob/master/src/Seq.App.Slack/SlackReactor.cs#L36

But, the links in question are generated by Seq, so the setting isn't applied.

I think we should probably remove the app-specific property and always use the value provided by Seq; I'll mark this as up-for-grabs in case anyone is able to take a look.

**Comment by rocklan** [comment]
Easily fixed, I've removed BaseUrl and submitted a pull request
