### ISSUE TITLE
Allow for Slack Markdown in Message

### ISSUE THREAD

**Issue by whoiskevinrich** [bytenik/Seq.App.Slack#22]
I might be missing something, but I'd love the ability to:

1. Use Slack Markdown in the message
2. Optionally attach specific properties to the message as attachments (instead of just text).

**Comment by whoiskevinrich** [comment]
@bytenik : This is mostly closed now by the PR:

A couple of things of note:

1. bold, code, italic, strikethrough, and links work well as documented at slacks site
2. `\n` newline characters are not respected
3. Properties are not addressed

if there is interest, I can open new issues for number 2 and 3 and tackle them as I get time (or leave them up-for-grabs)

**Comment by nblumhardt** [comment]
@whoiskevinrich I can help get these through the works, perhaps we should tackle 2 first (seems straightforward) then move onto 3?

Wondering, and more as a note-to-self, do we currently escape markdown correctly when we don't expect it? I.e. if I log an event with a message like `customer_card_id is 100` will we inadvertently end up with some italics and missing underscores?

**Comment by bytenik** [comment]
I can take a look at this sometime this week if no one else can get to it sooner. We're actually using Seq at my current startup, BallStreet, now.

**Comment by whoiskevinrich** [comment]
Okay, I'm going to close this issue and add the two new ones.
