### ISSUE TITLE
Dashboard alerts don't fire the app notification

### ISSUE THREAD

**Issue by thekatstevens** [bytenik/Seq.App.Slack#28]
I configured up a new dashboard and graph in Seq to track errors for a particular app, and then set up an alert to pipe through to the Slack App whenever the `count > 0` over some timespan (say 15m). The idea here was to throttle the notifications to more of a "digest" approach, rather than spamming the slack channel with every single error.

I can see the graph works great, but I never get any pings in Slack - so I checked the output of the app instance I'm piping to (by clicking the `View events raised by this instance` link), and I get the follow list of errors:

![image](https://user-images.githubusercontent.com/5182216/44249159-d8d70b80-a22d-11e8-9c19-70dc02bce43a.png)

So it looks like _something_ inside the app is throwing a nullreference, but _only_ on events raised through the graph. If I switch on `Stream incoming events` I do get all of the errors individually, so I know the integration is working.

**Comment by nblumhardt** [comment]
Hi Andrew,

I've had a shot at reproducing this and not had any luck so far.

My guess is that the app configuration is more likely to be a trigger than the dashboard alert parameters, as the former has a lot more options.

Do you have any non-default options (apart from the webhook URL) set, and do removing these/setting them back to the default help at all?

Cheers!

**Comment by nblumhardt** [comment]
Closing this one as stale; please let us know if you're still hitting issues :+1:
