### ISSUE TITLE
Fails to send events to slack, if event has two properties with different case variants of the same name.

### ISSUE THREAD

**Issue by larenelg** [bytenik/Seq.App.Slack#31]
Exception was thrown at:

https://github.com/bytenik/Seq.App.Slack/blob/ebe2f5adb7e4efdcfd10ebedecaa6ad196315b1a/src/Seq.App.Slack/EventFormatting.cs#L47

The event in the signal that was being sent had both `environment` and `Environment` as properties.

**Comment by nblumhardt** [comment]
Thanks! 👍

**Comment by droyad** [comment]
Oops, I didn't see this before I raised my issue. Fixed by #40, duplicated of #39.

**Comment by nblumhardt** [comment]
The fix is now published 🎉   Thanks @larenelg !
