### ISSUE TITLE
baseUrl no longer supplied

### ISSUE THREAD

**Issue by brettveenstra** [bytenik/Seq.App.Slack#32]
in earlier versions, you could configure a base url so that the "View this event in Seq" could have a correct link to proxied server... this is no longer available

**Comment by brettveenstra** [comment]
NOTE: the `canonicalUri` setting was not enough to make this work, also had to add to `listenUrls` (also at the top)

**Comment by nblumhardt** [comment]
Thanks for the note; this sounds like it could be a bug, `canonicalUri` should be doing this job. We'll check it out - thanks!

**Comment by zaheer-hawseea-cko** [comment]
How do i configure this using the seq admin page? It's annoying, all logs are pointing to localhost when seq is installed on production servers.

![image](https://user-images.githubusercontent.com/43137853/49365363-058d3100-f700-11e8-9e00-5a506b6dc5b0.png)

**Comment by nblumhardt** [comment]
Hi @zaheer-hawseea-cko - there's no option to apply this via the admin pages, it requires a change via the admin command-line, sorry.
