### ISSUE TITLE
NuGet publishing key has expired

### ISSUE THREAD

**Issue by nblumhardt** [bytenik/Seq.App.Slack#37]
Hi @bytenik - the latest `master` build failed because the NuGet publishing key expired:

https://ci.appveyor.com/project/bytenik/seq-app-slack/builds/24881952

Let me know if I can help; I'm `nblumhardt` on NuGet, in case adding me as a co-owner of the package would simplify things.

Cheers,
Nick

**Comment by bytenik** [comment]
Fixed!

**Comment by nblumhardt** [comment]
👏 thanks @bytenik !
