### ISSUE TITLE
The setting `BaseUrl` specified for the app instance is not exposed by the app.

### ISSUE THREAD

**Issue by danpowell88** [bytenik/Seq.App.Slack#38]
I cannot save any changes to app settings without getting "The setting `BaseUrl` specified for the app instance is not exposed by the app.".

The only option I've provided are the title and webhook url which appear to be valid. This occured on an older instance that was upgraded to 0.2.31 and also when I tried to create another new install of 0.2.31.

Our existing instances no longer appear to be publishing to slack either, I'm not entirely sure where to find the logs for this as the standard C:\ProgramData\Seq\Logs file doesnt seem to have any error information.

**Comment by nblumhardt** [comment]
Hi Daniel,

I think this is a bug - Seq should ignore the unnecessary property.

I'll raise an issue on the Seq repo for this; in the meantime, you can use the "Edit as JSON" button on the app instance settings screen to manually remove the "BaseUrl" entry.

Let me know if this still doesn't help.

Best regards,
Nick

**Comment by danpowell88** [comment]
Cheers, any advice on debugging why things aren't being sent to slack? 

I've tested the webhook manually and that works

**Comment by nblumhardt** [comment]
Hi Daniel,

Normally, problems with the app instance should show up when clicking `View diagnostic events from this app instance.` under the app instance's title (edit page).

I've just checked an instance of this app (lastest version) and its still firing away happily, here.

Hope this helps,
Nick

**Comment by mortenn** [comment]
If anyone else stumble upon this issue in the future:
I stumbled across this issue fixing an old integration that had broken.
The solution was to simply click the "edit as json" button and deleting the BaseUrl property.
