### ISSUE TITLE
An item with the same key has already been added

### ISSUE THREAD

**Issue by droyad** [bytenik/Seq.App.Slack#39]
My integration is failing on this line:

https://github.com/bytenik/Seq.App.Slack/blob/564ba2da65cfc9fc967fa2674acc63bb01352e30/src/Seq.App.Slack/EventFormatting.cs#L47

with the message `An item with the same key has already been added`.

Looking at my message, I have properties that only differ by case (silly mistake on my part).

![image](https://user-images.githubusercontent.com/1687639/59739181-26396480-92a7-11e9-92fc-3ff672a9ff96.png)

What should the code do here? Be case sensitive or just choose one of the values?

Happy to fix it if given guidance.

**Comment by nblumhardt** [comment]
Hey @droyad - thanks for the heads-up.

I think, in this case, it should probably just choose the first value that matches (if we could go back in time, case sensitivity might be a better choice, but we'd break too much existing configuration if we made that change now).

Sounds okay to you?
