### ISSUE TITLE
Allow users to configure whether or not to send through the attachments

### ISSUE THREAD

**Issue by timgaunt** [bytenik/Seq.App.Slack#4]
Sometimes we use Seq to send information to Slack which is just the title, it would be good if we could set it so it didn't send through the properties as this makes the messages overly bloated. It just needs to be a checkbox on the settings menu.

**Comment by bytenik** [comment]
I probably won't get to this for a bit, but if you want to do it I'd be happy to take a pull request. Otherwise I'll keep this on my list of things todo.

**Comment by timgaunt** [comment]
Done and done :)

Got a few more ideas to implement as well which I'll do as I can. Is there a simple way of testing the nuget package before making the pull request?

**Comment by bytenik** [comment]
Unfortunately no, not unless you want to run a nuget server. However, I did just merge in your changes and then post a new nuget.
