### ISSUE TITLE
Make Seq url configurable/overridable for slack messages

### ISSUE THREAD

**Issue by Jestar342** [bytenik/Seq.App.Slack#42]
https://github.com/bytenik/Seq.App.Slack/blob/564ba2da65cfc9fc967fa2674acc63bb01352e30/src/Seq.App.Slack/SlackReactor.cs#L189

Running Seq in a container/cluster or even just behind a gateway means that line will never work; it would be great to be able to configure an override so we can inject the external hostname/base-url.

**Comment by nblumhardt** [comment]
Setting the [`BASE_URI` environment variable](https://docs.datalust.co/docs/getting-started-with-docker#section-environment-variables) for the container should deal with this; does this help? Cheers!

**Comment by Jestar342** [comment]
That does help, thanks!

**Comment by nblumhardt** [comment]
Great, thanks 👍
