### ISSUE TITLE
App crashes randomly

### ISSUE THREAD

**Issue by oliverjanik** [bytenik/Seq.App.Slack#43]
```
System.IO.FileNotFoundException: Could not load file or assembly 'Serilog.Formatting.Compact.Reader, Version=1.0.2.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10' or one of its dependencies. The system cannot find the file specified.

File name: 'Serilog.Formatting.Compact.Reader, Version=1.0.2.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'

   at Seq.Apps.GenericHost.AppHost.<SendAsync>d__18.MoveNext()

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)

   at Seq.Apps.GenericHost.AppHost.SendAsync(String clef)

   at Seq.Apps.GenericHost.Program.<Main>d__0.MoveNext()
```

Not sure if Seq bug or Slack App bug

**Comment by nblumhardt** [comment]
Thanks for the heads-up, Oliver.

This would be an issue on the Seq side, but it doesn't seem like something that should appear intermittently, unless it has something to do with the global .NET state on the machine (Seq Apps on Windows, if that's the platform you're using, are hosted in a .NET Framework process for backwards compatibility).

Do you notice anything else strange on the machine? (Is it a dev machine, or a rarely-modified production server?)

There may be some more information in Seq's diagnostic report - _Settings > Diagnostics > Download a full diagnostic report_. Checking through this or sending it to support@ for interpretation might yield some clues.

Cheers,
Nick

**Comment by oliverjanik** [comment]
Thanks for a quick reply Nick. 

It's a rarely touched production server (Windows AWS). The issue started happening recently (no issues for months prior to that). Not it occurs very frequently. I thought it might be connected to the debounce settings we fiddled with in this app's settings.

Also I believe the server can be patched by AWS during maintenance window, so maybe the installed .net has changed slightly?

I'll check out the diagnostic log and update to latest Seq. I'll report back.

**Comment by nblumhardt** [comment]
Hi Oliver; I just realized that this ticket is still open; did you have any luck with the newer Seq version?

**Comment by oliverjanik** [comment]
This was resolved by updading Seq. Thanks Nick.
