### ISSUE TITLE
TLS 1.2 support question

### ISSUE THREAD

**Issue by DylanTusler** [bytenik/Seq.App.Slack#45]
So I am using this from Seq, but now getting this warning from Slack:
"On February 19, 2020, Slack will end support for TLS versions 1.0 and 1.1. You must update your apps before February 19, 2020. If you don’t update your apps to use TLS 1.2, requests sent to any Slack endpoint will fail after that date. You can use this lookup tool to identify any apps that still need to be updated to use TLS 1.2.

Please note that we are using a rolling window of 30 days to identify traffic from your apps that are using TLS 1.0 and 1.1. The list below will be updated every day."

This integration is identified as one that doesn't use TLS 1.2

Is this something I can fix server side, or does it require a code change?

Details at this site: https://api.slack.com/changelog/2019-07-deprecate-early-tls-versions

(According to the above link, you need to increase .net framework to 4.5 or later in order to address this.)

**Comment by nblumhardt** [comment]
Thanks for the report! I've just queued up #46 to (hopefully) resolve this on .NET 4.5+.

**Comment by ryangribble** [comment]
we've also started getting contacted by Slack regarding this...

I see PR #46 is still open at this point, so just sending a gentle nudge :)

**Comment by nblumhardt** [comment]
Thanks for the nudge, Ryan! Merged now :-) 👍

**Comment by ryangribble** [comment]
Great!  

I've updated, and will confirm once the Slack TLS migration advisory list updates and no longer flags this webhook usage as requiring attention.  Sounds like it could take 7 days
