### ISSUE TITLE
How does the optional message work with queries?

### ISSUE THREAD

**Issue by Regenhardt** [bytenik/Seq.App.Slack#47]
I trigger the notifier with an alert from a dashboard that uses a query like ´"select count(*) as count from stream where Category = 'SomeErrorCategory'´. The slack message itself just includes a link to the query in seq. 

I tried to add "Count: [count]" to the Message(Optional) field, and it now sends the link and additionaly literally "Count: [count]". 

Can I somehow include that in the message? I'd like to make a whole message like "[count] errors in 'SomeErrorCategory', brace for incoming tickets", but can't do that when I don't get the basics.

**Comment by Regenhardt** [comment]
Also tried to just put "[RenderedMessage]" or "[Query]" into the field and it sent literally that.

**Comment by nblumhardt** [comment]
Howdy! At present I don't think this is possible; the `count` isn't a direct property on the alert event, but rather, buried in a tabular structure reflecting the result of the query. May be a good one to look at more closely for a future version :+1:

**Comment by Regenhardt** [comment]
Good to know, that would be a nice addition.

Which properties can I use for that field then? Even just entering [RenderedMessage] sent literally that to Slack, so I'm not even sure I'm doing it right at all.

**Comment by nblumhardt** [comment]
Alerts use a fixed message - the substitution syntax (e.g. supportin `[RenderedMessage]` etc.) is only applied for regular, non-alert events.

The relevant `if` clause is this one:

https://github.com/bytenik/Seq.App.Slack/blob/master/src/Seq.App.Slack/SlackReactor.cs#L208

I am not sure whether there are any useful fields attached to alerts that aren't already incorporated into the default message. I can see where having some support for incorporating rows from `Results` would be good, though. Needs some more thought at our end.
