### ISSUE TITLE
Can we send Alerts without streaming events?

### ISSUE THREAD

**Issue by Regenhardt** [bytenik/Seq.App.Slack#48]
I'm trying to set up alerts from some dashboards for several different errors, so we get a Slack notification if many errors of a specific type happen in a short time.

So far I have to activate "Stream incoming events" in the app settings, otherwise the alerts form the dashboards don't get sent to Slack.

Is this intented behavior? I don't want the app to stream all the events, and I'd like to prevent building a signal that excludes 100% of events just to have the app send nothing but the alerts.

**Comment by nblumhardt** [comment]
Hi! This sounds unusual - we use the Slack app ourselves just for alerts (and don't stream events) so this should be working. Any chance you can send diagnostics and some app/alert setup details to Seq support? Seems unlikely that it will be a problem directly related to the Slack app. HTH!

**Comment by Regenhardt** [comment]
So I tried some stuff, and it turns out after restarting the seq instance the alert do indeed work without streaming enabled. Once again, it was the easy answer. Also I wouldn't have known how to get diagnostic data for you. Sorry for making a fuzz.
