### ISSUE TITLE
"View this event in Seq" link in slack message doesn't work

### ISSUE THREAD

**Issue by mboltuc** [bytenik/Seq.App.Slack#49]
Clicking the the "View this event ins Seq" link from slack doesn't appear to work for me.  It appears that the event id needs to be surrounded with single quotes.

The link produced looks like this:
http://seq.company.com/#/events?filter=@Id%20%3D%3D%20%22event-3b1ba684e14008d7cd583e0000000000%22&show=expanded

When i think it needs to be:
https://seq.company.com/#/events?filter=@Id%20%3D%20'event-3b1ba684e14008d7cd583e0000000000'

Looks like it might be an easy fix on this line of code:
https://github.com/bytenik/Seq.App.Slack/blob/1946dae1ca630a4cd3de19afdbb29e3ac664bebb/src/Seq.App.Slack/SlackReactor.cs#L225

**Comment by nblumhardt** [comment]
Thanks for the note, @mboltuc . The `%22`s in that URL are encoded double-quotes `"` so the expression should be correct; what kind of behaviour do you get? Any chance of a screenshot? Cheers!

**Comment by mboltuc** [comment]
@nblumhardt Thanks for the response, looks the double-quotes wasn't my issue.  My issue is that our seq installation didn't redirect the `http` url to `https`.  That's probably on me to fix...

**Comment by nblumhardt** [comment]
Thanks for the follow-up 👍
