### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by drullo** [bytenik/Seq.App.Slack#53]
I am attempting to use this for the first time.  I've followed the instructions for a minimal configuration, and it doesn't seem to be sending anything to Slack.  In Seq, the instance shows 0 messages sent.  Is there some step that I'm missing?  I'm not seeing any error messages or anything - it simply appears to be doing nothing.

I see that the app relies on the legacy Slack custom integration "Incoming Webhooks" and Slack warns against using custom integrations and urges developers to use apps instead, as the integrations are being phased out.  Is that, perhaps, affecting this utility's ability to send messages?  What is the long-term plan to update this utility to adapt to Slack's movement away from custom integrations?

**Comment by nblumhardt** [comment]
Hi Dan! Thanks for the note. The integration still works for us (just ran it again, here :-))

Although Slack has moved away from WebHooks, there's not yet been any deprecation/EoL announcement yet that we're aware of, so no concrete plans have been made to move on. When it becomes necessary, it's likely that, at a minimum, Datalust will start work on a replacement Slack App.

If the app was broken, you'd normally expect to still see a count of messages sent to the app in Seq, and would also probably see some errors raised in the Seq event stream from it.

What events are you expecting to reach the app? If you select an event in the events screen, choose the "Send to App" context menu, and pick your instance of the Slack app, does anything happen?

Best regards,
Nick

**Comment by nblumhardt** [comment]
Just adding a tidbit - it doesn't seem that all incoming webhook functionality is on the chopping block: https://api.slack.com/messaging/webhooks appears to be the modern version, this is seems to work for us.

**Comment by drullo** [comment]
Thanks @nblumhardt, that information was very helpful.  My expectation was that all events would be sent to Slack, or that I'd have the ability to specify criteria that determines which events are sent.  Your suggestion does prove that the utility IS working - which is great!  I didn't have any alerts configured.  Is that a requirement, or is it possible to just send all errors/warnings (for example)?

**Comment by drullo** [comment]
Perfect, thank you for your help!
