### ISSUE TITLE
Channel as a parameter

### ISSUE THREAD

**Issue by waynebrantley** [bytenik/Seq.App.Slack#7]
your add in works like a champ!
One of the parameters to the slack API call is the channel to put the message in.
Would be great if that channel was specified on the setup in SEQ so we could just use the same API endpoint.

Thoughts?

**Comment by bytenik** [comment]
I have no problem with that as a feature, but I may not get around to it for a week or so. I'd accept a PR and/or I'd also accept polite nudging next week to do it myself. :)

**Comment by waynebrantley** [comment]
I know nothing about the API or code...but thought it would be nice easy feature 
Nudge.... 
;-)

**Comment by bytenik** [comment]
Thanks @eliekstein for fixing this issue.

**Comment by eliekstein** [comment]
@bytenik Don't forget the nuget update which is how most people usually install it on SEQ

**Comment by bytenik** [comment]
It will be some time until I have an opportunity to update the NuGet.

**Comment by eliekstein** [comment]
@bytenik you got a lot of users on this, why deprive them of this update :wink:.
Is it too much to ask to add me as an owner to the package, or send me a temporary api key?
